Python3およびFlaskへの移行
vippool/clerk pull request #14
Opened 2020-08-18 10:28 UTC by ry0y4n

## 変更点
- app.yamlをpython3に対応
- main.pyとbase_handler.pyをflaskに移行（まだ各ハンドラーはそのまま）

## 備考
以下は（簡略化した）各ハンドラーも含め動作するAPIを実装したプライベートリポジトリ
https://github.com/ry0y4n/clerk-flask

2020-08-18 10:59 UTC, hoshizuki requested changes

2020-08-18 10:59 UTC, hoshizuki commented on server/app.yaml
> +  login: admin
各ファイル、改行で終わる習慣をつけるといいと思います。
（テキストファイルなので）

2020-08-18 10:59 UTC, hoshizuki commented on server/main.py
> -	# 非公開 API
非公開 API も対応をお願いします。

2020-08-18 10:59 UTC, hoshizuki commented on server/main.py
> +@app.route("/err-handle")
これはなんですか？

2020-08-25 06:36 UTC, ry0y4n commented
# 修正要素メモ
## "long"に対するエラー

python2系では**int**と**long**2つの整数型があった。
しかし、python2.4にて**int**から**long**への自動昇格がサポートされたのを皮切りに、python3系ではlong型は廃止され、現在は整数すべて**int**型となった。

## printに対するエラー
python3系からprint関数にはパレンティスの括弧が必要になった。

## google.appengine.api に対するエラー[WIP: submittx.py]
python3系からAppEngin SDKは全面的に非推奨。
別のタスク管理サービスを使わないといけないようだ。

## unicodeに対するエラー
python3系では文字列はunicode文字列として扱われるようになった。
python2系でいうところの`u""`。この表記をしてもエラーはでないが同じ意味。なので**str**で置換した。

## has_keyに対するエラー
python3系から**has_key**が消え、互換性がなくなった。
これをpython3系で実現するには**key in dict**を使う。

2020-08-25 07:15 UTC, hoshizuki requested changes

2020-08-25 07:15 UTC, hoshizuki commented on server/main.py
> +
ValidationError 例外に対するハンドラもお願いします。

2020-08-25 07:15 UTC, hoshizuki commented on server/submittx.py
>  			raise ValidationError( 'pub_key', 'unicode' )
第２引数も修正お願いします。

2020-08-25 09:19 UTC, hoshizuki commented
見た感じ問題なさそうです。おつかれさまです。

2020-08-26 02:17 UTC, ry0y4n commented
各APIで軽くエラーハンドリングの検証したところ，`prepare.tx` のパラメータ分解のところでExceptionを投げてるのに対応できてなかったので，新たにExceptionのエラーハンドラーも追加しました．

2020-08-26 04:12 UTC, hoshizuki approved these changes

2020-08-26 04:12 UTC, merged