update_dbの修正&動作確認
vippool/clerk pull request #16
Opened 2020-09-04 07:32 UTC by ry0y4n

2020-09-04 11:54 UTC, hoshizuki requested changes
・現状 conn となっているものが db で、c は cursor の略です。
・config.py がファイル全体 diff になっていますが、改行コード等変換したのでしょうか？

2020-09-08 01:48 UTC, hoshizuki requested changes

2020-09-08 01:48 UTC, hoshizuki commented on server/update_db.py
> -
意味のない空行の追加・削除が散見されてレビューが見づらいです。対応をお願いします。

2020-09-08 01:48 UTC, hoshizuki commented on server/update_db.py
> +	# ブロックヘッダの確認
意味もなくタブが変わっていて diff が見づらいです。

2020-09-08 01:48 UTC, hoshizuki commented on server/update_db.py
> -	# DB が空っぽなら何もしないでいい
なぜこのコメントを変えたのですか？

2020-09-08 01:48 UTC, hoshizuki commented on server/update_db.py
> +
なぜ終端に diff が発生するのですか？

2020-09-08 01:48 UTC, hoshizuki commented on server/update_db.py
> +	c = db.cursor()
たぶん、cursor を取る前に、db.begin() を呼ばないとトランザクションが開始されません。

2020-09-08 03:55 UTC, hoshizuki requested changes

2020-09-08 03:55 UTC, hoshizuki commented on server/getrecentblkid.py
> -
getblock, getrecentblkid で空行が１つずつ消えています。

2020-09-08 05:46 UTC, hoshizuki requested changes

2020-09-08 05:46 UTC, hoshizuki commented on server/util.py
> +	binary = address_prefix( coind_type ).encode() + ripemd160.digest()
address_prefix で b'xx' を返す方が良いと思います。

2020-09-08 05:46 UTC, hoshizuki commented on server/gettransaction.py
> +
謎の空白

2020-09-08 05:46 UTC, hoshizuki commented on server/getrecenttxid.py
> +		db.begin()
SELECT を発行しているだけなら DB を更新しないので、トランザクション必要ないです。

2020-09-08 05:46 UTC, hoshizuki commented on server/getblock.py
> -
意味の違うパラグラフなので空行消さないでください。

2020-09-08 09:02 UTC, hoshizuki requested changes
あともう少しです！がんばってください。

2020-09-08 09:02 UTC, hoshizuki commented on server/update_db.py
> +					base64.b64encode( bz2.compress( json.dumps( block_json_reduce ).encode() ) )
encode は後で混乱しないよう、utf-8 で統一をお願いします。

2020-09-08 09:02 UTC, hoshizuki commented on server/util.py
> +	if binary[0:1] != address_prefix( coind_type ):
これ、型が違いませんか？もしかして暗黙変換されて問題ない？

2020-09-08 09:02 UTC, hoshizuki commented on server/update_db.py
> +						base64.b64encode( bz2.compress( json.dumps( tx_json_reduce ).encode() ) ).decode()
json のダンプは utf-8 で encode して、base64 の結果は ascii で decode してください。

2020-09-08 09:22 UTC, ry0y4n commented on server/util.py
> +	if binary[0:1] != address_prefix( coind_type ):
binary[0]だとintに変換されてしまってたのでスライスでbytesのまま取り出しました。
monacoindの場合、binaryが"2\xfa\....."でbinary[0]が<int>50になります。スライスすると<bytes>2になるのでaddress_prefixが返す<bytes>2とうまく等価判定が取れると思ったのですがどこか汲み取り違えているでしょうか？

2020-09-08 09:39 UTC, hoshizuki commented on server/util.py
> +	if binary[0:1] != address_prefix( coind_type ):
binary は b"2\xfa..." になりませんか？それであれば binary[0] = b'2' になってほしい所ですが……
なっていないのであれば、b58decode の最後の unhexlify の仕様が python2 から変わっているのかもしれません。

2020-09-08 09:46 UTC, ry0y4n commented on server/util.py
> +	if binary[0:1] != address_prefix( coind_type ):
はい、binaryは指摘の通りb"2\xfa..."です。タイポでした。
現象については手元でやってみると
print(b"abc"[0]) -> 97
となるのでやはりここでintに変換されるようです。

2020-09-08 09:54 UTC, hoshizuki commented on server/util.py
> +	if binary[0:1] != address_prefix( coind_type ):
ごめんなさい。よく考えたら address_prefix が返してくるのも byte array なので、この修正であっています。
失礼いたしました。

2020-09-08 10:25 UTC, hoshizuki requested changes

2020-09-08 10:25 UTC, hoshizuki commented on server/coind.py
> +			return float(obj)
特にコーディング規約が決まっているわけではないですが、他とそろっているときれいに見えます。

2020-09-08 10:25 UTC, hoshizuki commented on server/coind.py
> +			return float(obj)
あと関数の間は 1 行空けてほしいです。

2020-09-08 10:25 UTC, hoshizuki commented on server/coind.py
> +			'Authorization': b'Basic %b' % base64.standard_b64encode( b'%b:%b' % ( self.rpc_user.encode(), self.rpc_pass.encode() ) )
ここも、ascii 指定でお願いします。

2020-09-08 10:25 UTC, hoshizuki commented on server/update_db.py
> +	db.begin()
UPDATE 1文しかないものはトランザクション張らなくても大丈夫です。

2020-09-08 10:25 UTC, hoshizuki commented on server/update_db.py
> +	db.begin()
commit は忘れずに。

2020-09-08 10:25 UTC, hoshizuki commented on server/update_db.py
> +	c = db.cursor()
ここも update 1文なのでトランザクション要りません。

2020-09-08 10:44 UTC, ry0y4n commented on server/coind.py
> +			return float(obj)
最初のころはtypeerrorが出てこの関数を挟むとエラーが消えていたのですが、今確認したらなくても動作することを確認しましたので該当関数を削除しました。

2020-09-08 10:51 UTC, hoshizuki approved these changes
おつかれさまでした！

2020-09-08 10:51 UTC, hoshizuki commented on server/coind.py
> +			return float(obj)
了解です。

2020-09-08 10:51 UTC, merged