送金テスト動作確認完了
vippool/clerk pull request #18
Opened 2020-10-12 05:06 UTC by ry0y4n

2020-10-12 06:24 UTC, hoshizuki requested changes

2020-10-12 06:24 UTC, hoshizuki commented on server/submittx.py
> +			'log_data': json.dumps(log_data)
ここ、dump なしにできませんか？

2020-10-12 06:35 UTC, ry0y4n commented on server/submittx.py
> +			'log_data': json.dumps(log_data)
`the JSON object must be str, bytes or bytearray, not dict`
dumpをなくすとsubmittx.pyの実行でエラーは出ませんが、sendrawtransaction.pyの実行で上記文で500エラーが返ってきます。ただ、送金自体はされています。

2020-10-12 06:37 UTC, ry0y4n commented on server/submittx.py
> +			'log_data': json.dumps(log_data)
sendrawtransaction側をいじってdumpなしでいけるように修正してみます。

2020-10-12 06:45 UTC, ry0y4n commented on server/submittx.py
> +			'log_data': json.dumps(log_data)
修正し送金の確認まで完了しました。

2020-10-12 06:49 UTC, hoshizuki commented on server/submittx.py
> +			'log_data': json.dumps(log_data)
ありがとうございます！

2020-10-12 07:04 UTC, hoshizuki commented on server/sendrawtransaction.py
> +		log_data['result'] = json.loads(r[1])
ここ、r の型って何になっていますか？

2020-10-12 07:19 UTC, ry0y4n commented on server/sendrawtransaction.py
> +		log_data['result'] = json.loads(r[1])
tupleとなっています。例でいうと
`('coind error: 500', b'{"result":null,"error":{"code":-27,"message":"transaction already in block chain"},"id":null}\n')`
なのでr[1]を取り出してログデータに入れていました。

2020-10-12 07:43 UTC, hoshizuki commented on server/sendrawtransaction.py
> +		log_data['result'] = json.loads(r[1])
それだと成功した場合に、TXID の2文字目がロギングされるだけになりませんか？
後で json.dumps するので、r のまま格納してください。

2020-10-12 07:45 UTC, ry0y4n commented on server/sendrawtransaction.py
> +		log_data['result'] = json.loads(r[1])
すいません、送金に成功したときはstringでした。対応してみます。

2020-10-12 09:05 UTC, ry0y4n commented on server/sendrawtransaction.py
> +		log_data['result'] = json.loads(r[1])
修正しました。

2020-10-12 11:49 UTC, hoshizuki commented on server/sendrawtransaction.py
> +		log_data['result'] = json.loads(r[1])
"coind error: 500" の方も欲しいので、エラーの場合も json.loads しないようにお願いします。

2020-10-19 06:34 UTC, ry0y4n commented
エラー文がbytes型で送られていたをcoind.pyの返り値を修正して，r=e.args(eはExeptionなので.args)で動くようにしました．

2020-10-19 07:47 UTC, hoshizuki approved these changes

2020-10-19 07:48 UTC, merged

2020-10-19 07:48 UTC, hoshizuki commented
おつかれさまでした！OK です。